<?php
$data = array(
    /*
    
    "zee_bangla"    =>array("Zee Bangla","/en/channel/zee-bangla","https://cdn.bioscopelive.com/upload/channels/sd/j6nIdklOX39.png"),
    "sony_six"      =>array("Sony Six","/en/channel/sony-six","https://cdn.bioscopelive.com/upload/channels/sd/s8IBAPVHazB.png"),
    "sony_aath"     =>array("Sony Aath","/en/channel/sony-aath","https://cdn.bioscopelive.com/upload/channels/sd/62pJAoY3kCM.png"),
    "colors_bangla" =>array("Colors Bangla","/en/channel/colors-bangla","https://cdn.bioscopelive.com/upload/channels/sd/kU9AD02Upbj.png"),
    "ten_sports_1"  =>array("SONY TEN 1","/en/channel/ten-sports-1","https://cdn.bioscopelive.com/upload/channels/sd/Rhmi59G3O4D.png"),
    "sangeet_bangla"=>array("Sangeet Bangla","/en/channel/sangeet-bangla","https://cdn.bioscopelive.com/upload/channels/sd/Xqf99tBaKw2.png"),
    "ten_sports_2"  =>array("SONY TEN 2","/en/channel/ten-sports-2","https://cdn.bioscopelive.com/upload/channels/sd/27bE6UrXVzf.png"),
    "zee_cinema"    =>array("Zee Cinema","/en/channel/zee-cinema","https://cdn.bioscopelive.com/upload/channels/sd/SJT2p0fTxAJ.png"),
    "sony_espn"     =>array("Sony ESPN","/en/channel/sony-espn","https://cdn.bioscopelive.com/upload/channels/sd/mJP2Tr2Iwjt.png"),
    "zee_tv"        =>array("Zee TV","/en/channel/zee-tv","https://cdn.bioscopelive.com/upload/channels/sd/5jV3f9QxcHs.png"),
    "zee_classic"   =>array("Zee Bollywood","/en/channel/zee-classic","https://cdn.bioscopelive.com/upload/channels/sd/cfUYiikqmD3.png"),
    "colors_asia"   =>array("Colors Asia","/en/channel/colors-asia","https://cdn.bioscopelive.com/upload/channels/sd/jjVVEdLt5UD.png"),
    "mtv"           =>array("MTV","/en/channel/mtv","https://cdn.bioscopelive.com/upload/channels/sd/an3L3hgUS82.png"),
    
    */

    "ekattur_tv"    =>array("Ekattor TV",           "/en/channel/ekattur-tv",       "https://cdn.bioscopelive.com/upload/channels/sd/1Y2Slm56uJ8.png"),
    "independent_tv"=>array("Independent TV",       "/en/channel/independent-tv",   "https://cdn.bioscopelive.com/upload/channels/sd/639iTnh90UR.png"),
    "nickelodeon"   =>array("Nickelodeon",          "/en/channel/nickelodeon",      "https://cdn.bioscopelive.com/upload/channels/sd/S4fGKjtz0os.png"),
    "my_tv"         =>array("My TV",                "/en/channel/my-tv",            "https://cdn.bioscopelive.com/upload/channels/sd/vDXLuLBXf6J.png"),
    "btv_world"     =>array("BTV World",            "/en/channel/btv-world",        "https://cdn.bioscopelive.com/upload/channels/sd/99ZKMd4mWYM.png"),
    "atn_bangla"    =>array("ATN Bangla",           "/en/channel/atn-bangla",       "https://cdn.bioscopelive.com/upload/channels/sd/ZCqILa0u7vD.png"),
    "dhoom"         =>array("Dhoom",                "/en/channel/dhoom",            "https://cdn.bioscopelive.com/upload/channels/sd/V6mD2QiByZs.png"),
    "sa_tv"         =>array("SA TV",                "/en/channel/sa-tv",            "https://cdn.bioscopelive.com/upload/channels/sd/hw62kGT7ZqJ.png"),
    "bongo_movies"  =>array("Bongo Movies",         "/en/channel/bongo-movies",     "https://cdn.bioscopelive.com/upload/channels/sd/Mq2jeWV007t.png"),
    "ananda_tv"     =>array("Ananda TV",            "/en/channel/ananda-tv",        "https://cdn.bioscopelive.com/upload/channels/sd/HRjXQdYEqsE.png"),
    "mohona_tv"     =>array("Mohona",               "/en/channel/mohona-tv",        "https://cdn.bioscopelive.com/upload/channels/sd/UU3a2v6E7Zs.png"),
    "gaan_bangla"   =>array("Gaan Bangla",          "/en/channel/gaan-bangla",      "https://cdn.bioscopelive.com/upload/channels/sd/um9o21i3T1E.png"),
    "atn_news"      =>array("ATN News",             "/en/channel/atn-news",         "https://cdn.bioscopelive.com/upload/channels/sd/2c08GCMcP3z.png"),
    "nagorik_tv"    =>array("Nagorik Tv",           "/en/channel/nagorik-tv",       "https://cdn.bioscopelive.com/upload/channels/sd/6ms91aehi2a.png"),
    "zoom"          =>array("Zoom",                 "/en/channel/zoom",             "https://cdn.bioscopelive.com/upload/channels/sd/dCDNt5JRD2q.png"),
    "bbc_world"     =>array("BBC World",            "/en/channel/bbc-world",        "https://cdn.bioscopelive.com/upload/channels/sd/8bOOXkJ1cLJ.png"),
    "boishakhi_tv"  =>array("Boishakhi Television", "/en/channel/boishakhi-tv",     "https://cdn.bioscopelive.com/upload/channels/sd/20mgRCbFLz5.png"),
    "atn_music"     =>array("ATN Music",            "/en/channel/atn-music",        "https://cdn.bioscopelive.com/upload/channels/sd/H86bSTqPN6O.png"),
    "dbc_news"      =>array("DBC News",             "/en/channel/dbc-news",         "https://cdn.bioscopelive.com/upload/channels/sd/6GxyIRO4P74.png"),
    "asian_tv"      =>array("Asian TV",             "/en/channel/asian-tv",         "https://cdn.bioscopelive.com/upload/channels/sd/84xExHj3DJ8.png"),
    "ruposhi_bangla"=>array("Ruposhi Bangla",       "/en/channel/ruposhi-bangla",   "https://cdn.bioscopelive.com/upload/channels/sd/105QtNR46SH.png"),
    "hum_sitarey"   =>array("Hum Sitarey",          "/en/channel/hum-sitarey",      "https://cdn.bioscopelive.com/upload/channels/sd/r1H2LWl2U4T.png"),
    "atn_islamic_tv"=>array("ATN Islamic TV",       "/en/channel/atn-islamic-tv",   "https://cdn.bioscopelive.com/upload/channels/sd/DJcpP2t4Mdp.png"),
    "sangsad_tv"    =>array("Sangsad TV",           "/en/channel/sangsad-tv",       "https://cdn.bioscopelive.com/upload/channels/sd/So3Og8HY4uN.png"),
    "al_jazeera"    =>array("Al Jazeera",           "/en/channel/al-jazeera",       "https://cdn.bioscopelive.com/upload/channels/sd/0iLtx9H8sr5.png"),
    "dw"            =>array("DW",                   "/en/channel/dw",               "https://cdn.bioscopelive.com/upload/channels/sd/jq7qr2d6FF6.png"),
);
